
title: Your awesome title
author: lcromartie
email: lyndol.cromartie@bellevuecollege.edu
description: Working with Jekyll themes.

# social links
github_username:  lcromartie

show_excerpts: false # set to false to remove excerpts on the homepage


theme: minima:
